# -*- coding: utf-8 -*-
"""hw10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17bNlKTSoKHEPYjd1RJ0RGu02HnVtWmHh
"""

import os

import pickle

filepath = 'score.bin'

def input_scores():
  s = []
  i = 1
  while (True) :
    n = int(input(f'#{i}? '))
    if n < 0 :
      break
    s.append(n)
    i += 1
  return s

def get_average(s):
  total = 0
  for n in s :
    total += n
  return total / len(s)

def show_scores(s):
  for n in s :
    print(n, end=' ')
  print()

if os.path.exists(filepath):
  print('[파일 읽기]')
  print()
  print('[점수 출력]')
  with open(filepath, 'rb') as file:
    sc = pickle.load(file)
    ag = pickle.load(file)
    print('개인점수: ', end='')
    print(sc[0], end=' ')
    print(sc[1])
    print('평균: ', end='')
    print(ag)
else :
  print('[점수 입력]')
  scores = input_scores()

  print('\n[점수 출력]')
  print('개인점수: ', end='')
  show_scores(scores)

  avg = get_average(scores)
  print(f'평균: {avg:.1f}')

  with open(filepath, 'wb') as file:
    pickle.dump(scores, file)
    pickle.dump(avg, file)