# -*- coding: utf-8 -*-
"""hw4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ksjk7k6i4NUE1F5qFkSRtjG76TsMC87-
"""

def rep_char(c,n):
  print(c * n)

def draw_line_string():
  msg1 = 'input his/her name:'
  msg2 = 'hello ' + input(msg1)
  nstr = len(msg1) if (len(msg1) > len(msg2)) else len(msg2)
  rep_char('-', nstr)
  print(f'{msg2}')
  print('Welcome to seoul.')
  rep_char('-', nstr)

draw_line_string()