# -*- coding: utf-8 -*-
"""hw6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eCIav3TPaW6asmU-EJBB_R92AWo_eYME
"""

def display_multiplication_table(i,p) :
  n = p - 3
  while n <= p :
    print(f'{n} x {i} = {n * i:2d}', end = '      ')
    n += 1

N = 1
while N <= 9 :
  display_multiplication_table(N,5)
  print()
  N = N + 1

print()

N = 1
while N <= 9 :
  display_multiplication_table(N,9)
  print()
  N = N + 1