# -*- coding: utf-8 -*-
"""hw7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J66ei-kvvQByU9Z_qg0UMjuFnanNPhQj
"""

shopping_bag = {}
print('[구입]')
while True:
  item = input('상품명? ')
  if item == '':
    break
  else :
    amount = int(input('수량은? '))
    shopping_bag[item] = amount
    print(f'장바구니에 {item} {amount}개가 담겼습니다.\n')

print(f'\n>>>장바구니 보기:{shopping_bag}')

print('\n[검색]')
key = input('장바구니에서 확인하고자 하는 상품은? ')
if key in shopping_bag :
  a = shopping_bag[key]
  print(f'{key}은(는) {a}개 담겨 있습니다.')
else :
  print('존재하지 않는 상품 입니다.')