# -*- coding: utf-8 -*-
"""hw8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S16d44e9met3sFlhf4lqttZJsigiJG3f
"""

def buy(s):
  print('[구입]')
  item = input('상품명? ')
  if item == '':
    return False
  else :
    amount = int(input('수량은? '))
    s[item] = amount
    print(f'장바구니에 {item} {amount}개가 담겼습니다.\n')

def show(s) :
  print(f'\n>>>장바구니 보기:{s}')

def find(s) :
  print('\n[검색]')
  key = input('장바구니에서 확인하고자 하는 상품은? ')
  if key in s :
    a = s[key]
    print(f'{key}은(는) {a}개 담겨 있습니다.')
  else :
    print(f'장바구니에 {key}은(는) 없습니다.')

shopping_bag = {}
while True:
  if buy(shopping_bag) == False:
    break
show(shopping_bag)
find(shopping_bag)