# -*- coding: utf-8 -*-
"""hw9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rBpnDxFSgopZXmn_lA-peYUDihq5yfqw
"""

class Point :
  def __init__(self, x=0, y=0):
    self.__x = x
    self.__y = y
  
  def show(self):
    print(f'({self.__x},{self.__y})')
  
  def set(self, x, y):
    self.__x = x
    self.__y = y

  def get(self):
    return (self.__x, self.__y)

class Rectangle :
  lt = Point()
  rb = Point()
  def __init__(self, x1, y1, x2, y2):
    self.__x1 = x1
    self.__y1 = y1
    self.__x2 = x2
    self.__y2 = y2
    lt = Point(x1, x1)
    rb = Point(x2, y2)

  def show(self):
    print(f'좌측 상단 꼭지점이 {self.__x1, self.__y1}이고 우측 상단 꼭지점이 {self.__x2, self.__y2}인 사각형 입니다.')

  def getWidth(self):
    W = self.__x2 - self.__x1
    return W
  
  def getHeight(self):
    H = self.__y2 - self.__y1
    return H
  
  def getArea(self):
    A = (self.__x2 - self.__x1) * (self.__y2 - self.__y1)
    return A

  def getPerimeter(self):
    P = (self.__x2 - self.__x1)*2 + (self.__y2 - self.__y1)*2
    return P


r1 = Rectangle(5, 5, 20, 10)
a = r1.getArea()
p = r1.getPerimeter()
r1.show()
print(f'\n넓이는 {a}, 둘레는 {p}')
